version: 0.0
os: linux
files:
- source: /gl_EllotteAI_20171020_PROJECT_WAS.tar
  destination: /h2010/gl
- source: /gl_EllotteAI_20171020_PROJECT_WEB.tar
  destination: /h2010/gl

permissions:
- object: /h2010/gl
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/vfoprj_gl1_Stop.sh
     timeout: 60
  ApplicationStart:
   - location: scripts/vfoprj_gl1_Start.sh
     timeout: 120
     