version: 0.0
os: linux
files:
- source: /fo_ren_mobile2017_TEST_PROJECT_WAS.tar
  destination: /h2010/fo2
- source: /fo_ren_mobile2017_TEST_PROJECT_WEB.tar
  destination: /h2010/fo2

permissions:
- object: /h2010/fo2
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/ApplicationStop.sh
     timeout: 60
  ApplicationStart:
   - location: scripts/ApplicationStart.sh
     timeout: 120
     