version: 0.0
os: linux
files:
- source: /BA_prj_WAS.tar
  destination: /esuper/project/batch

permissions:
- object: /esuper/
  pattern: "**"
  owner: xclass
  group: www
  mode: 775

hooks:
  ApplicationStop:
   - location: scripts/aws_baprj1_Stop.sh
     timeout: 120
  ApplicationStart:
   - location: scripts/aws_baprj1_Start.sh
     timeout: 120
     