version: 0.0
os: linux
files:
- source: /config.zip
  destination: /usr1/home/jeus/configfile

permissions:
- object: /usr1/home/jeus/configfile
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/Stop.sh
     timeout: 900
  ApplicationStart:
   - location: scripts/Start.sh
     timeout: 900