version: 0.0
os: linux
files:
- source: /PRO_prj_WAS.tar
  destination: /esuper/project/back

permissions:
- object: /esuper/
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/aws_proprj1_Stop.sh
     timeout: 120
  ApplicationStart:
   - location: scripts/aws_proprj1_Start.sh
     timeout: 120
     