version: 0.0
os: linux
files:
- source: /ROOT.war
  destination: /lotte/lecs/webapp/nuniqlo

permissions:
- object: /lotte/lecs/webapp/nuniqlo
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/ApplicationStop.sh
     timeout: 60
  ApplicationStart:
   - location: scripts/ApplicationStart.sh
     timeout: 60
  ValidateService:
   - location: scripts/Precompile.sh
     timeout : 240