version: 0.0
os: linux
files:
- source: /elb_winwin
  destination: /usr1/home/jeus/awsscript/elb/winwin

permissions:
- object: /usr1/home/jeus/awsscript/elb/winwin
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStart:
   - location: scripts/ApplicationStart.sh
     timeout: 900