version: 0.0
os: linux
files:
- source: /PARTNER_prj_WAS.tar
  destination: /esuper/project/partner

permissions:
- object: /esuper/
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/aws_partnerprj1_Stop.sh
     timeout: 120
  ApplicationStart:
   - location: scripts/aws_partnerprj1_Start.sh
     timeout: 120
     