version: 0.0
os: linux
files:
- source: /mo2_ren_mobile2017_20170717_PROJECT_WAS.tar
  destination: /h2010/mo2
- source: /mo2_ren_mobile2017_20170717_PROJECT_WEB.tar
  destination: /h2010/mo2

permissions:
- object: /h2010/mo2
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/ApplicationStop.sh
     timeout: 60
  ApplicationStart:
   - location: scripts/ApplicationStart.sh
     timeout: 120
     