version: 0.0
os: linux
files:
- source: /bo_TogetherAppPrj_201810_PROJECT_WAS.tar
  destination: /h2010/bo
- source: /bo_TogetherAppPrj_201810_PROJECT_WEB.tar
  destination: /h2010/bo

permissions:
- object: /h2010/bo
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/vboprj_bo1_Stop.sh
     timeout: 60
  ApplicationStart:
   - location: scripts/vboprj_bo1_Start.sh
     timeout: 120
     