version: 0.0
os: linux
files:
- source: /mo_TogetherAppPrj_201810_PROJECT_WAS.tar
  destination: /h2010/mo
- source: /mo_TogetherAppPrj_201810_PROJECT_WEB.tar
  destination: /h2010/mo

permissions:
- object: /h2010/mo
  pattern: "**"
  owner: jeus
  group: www
  mode: 644

hooks:
  ApplicationStop:
   - location: scripts/vfoprj_mo1_Stop.sh
     timeout: 60
  ApplicationStart:
   - location: scripts/vfoprj_mo1_Start.sh
     timeout: 300
     