version: 0.0
os: linux
files:
- source: /OB_prj_WAS.tar
  destination: /usr2/LOTTESUPER

permissions:
- object: /usr2/LOTTESUPER/
  pattern: "**"
  owner: xclass
  group: www
  mode: 777

hooks:
  ApplicationStop:
   - location: scripts/aws_obprj1_Stop.sh
     timeout: 120
  ApplicationStart:
   - location: scripts/aws_obprj1_Start.sh
     timeout: 120
     